version: "3.8"
services:
  library-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - app_port=${APP_PORT}
        - app_name=${APP_NAME}
        - postgres_user=${POSTGRES_USER}
        - postgres_password=${POSTGRES_PASSWORD}
        - postgres_db=${POSTGRES_DB}
        - postgres_port=${POSTGRES_PORT}
    image: library-api:latest
    env_file:
      - .env
    ports:
      - "7878:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "7070:5432"
    volumes:
      - library-data:/var/lib/library-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  library-data:
    driver: local